 apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: credit-service-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - host: credit-service.info
     http:
       paths:
       - path: /
         backend:
           serviceName: credit-service
           servicePort: 8080