apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: credit-service
  name: credit-service
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: credit-service
  type: NodePort
status:
  loadBalancer: {}
